### ISSUE TITLE
Conflict with this repo's purpose and hacktoberfest 2018's github tracker

### ISSUE THREAD

**Issue by y2s82** [humphd/hacktoberfest-at-seneca-2018#15]
# Overview
Hacktoberfest may be tracking our pull-requests in github indiscriminately. This automates the process by taking away the busy work of reporting and validating contributions.  
This repository is created to privately track our work in Hacktoberfest as a class.  Professor also would like us to practice proper use of the tool by using pull request to make changes.

# Problem
Due to Hacktoberfest's way of tracking our pull-request activities, us creating a pull request in this repository to make a report may unfortunately be counted towards actual contribution towards Hacktoberfest.
  
Can this be clarified?  
Also, if this is true, what can we do to address the issue?

**Comment by 0xazure** [comment]
The [participation details](https://hacktoberfest.digitalocean.com/details) for Hacktoberfest say:

> Pull requests can be made in any GitHub-hosted repositories/projects. As long as the **project is public** and GitHub-hosted, your PRs will count towards your participation

(emphasis mine).

This says to me that PRs made to this repo _will_ count towards the Hacktoberfest count.

A simple fix seems to be to make the repository private, which is something @humphd will have to take care of. At that point, Hacktoberfest won't count PRs opened against this repository towards our totals for contribution.

**Comment by humphd** [comment]
I've emailed them for clarification.  I'll report back here.

**Comment by humphd** [comment]
I still haven't heard back from the Hacktoberfest organizers, but given @Pooch11's comment above, I'm going to move the reporting requirements for our students into a wiki in this repo.  I'll do that now, and disable pull requests.

I'll report back when it's done.

**Comment by humphd** [comment]
I've [moved things to the wiki](https://github.com/humphd/hacktoberfest-at-seneca-2018/wiki/Student-Submissions), and fixed the repo in f5d31aa.  I'll discuss in class with everyone, but feel free to start adding things there, and making whatever wiki pages you want.
