### ISSUE TITLE
Cant edit

### ISSUE THREAD

**Issue by saketepe** [humphd/hacktoberfest-at-seneca-2018#18]

**Comment by struong9** [comment]
I don't have an Edit button either.

**Comment by ywpark1** [comment]
I cannot edit the wiki page either. 

@humphd Can you resend the invitation for editing wiki page? Thanks!

**Comment by humphd** [comment]
@saketepe, @struong9 I've already sent you an invite on GitHub, you just need to accept it.

@ywpark1 I just created an invite for you.
