### ISSUE TITLE
Add missing students as Contributors

### ISSUE THREAD

**Issue by humphd** [humphd/hacktoberfest-at-seneca-2018#2]
[GitHub's UI is breaking for me](https://twitter.com/humphd/status/1046458337955655680) as I try to add all students as contributors.  I made it through 90% of my list, but I know some of them failed silently; however I can't easily tell which ones.

If you find that you don't have contributor rights on this repo, please leave a comment below and I'll fix.

**Comment by SeanPrashad** [comment]
Just for peace of mind, I manually went through all of the [Lab 2](https://wiki.cdot.senecacollege.ca/wiki/DPS909/OSD600_Fall_2018_Lab_2) submissions by students and all of the names appeared in `data/people.json` 🎉

**Comment by humphd** [comment]
Awesome, thank you @SeanPrashad.

**Comment by Pooch11** [comment]
can I get an invite to the contributors list?

**Comment by humphd** [comment]
@Pooch11 done.

**Comment by humphd** [comment]
Closing for now.  People can file a new bug if they need access and haven't spoken up yet.
