### ISSUE TITLE
Issue Up for grabs for hacktoberfest

### ISSUE THREAD

**Issue by PopeSpaceous** [humphd/hacktoberfest-at-seneca-2018#23]
This issue is not in the repository yet so you'd have to create it as well. 
[https://github.com/cjlcarvalho/crazy-robots](https://github.com/cjlcarvalho/crazy-robots)

Issue: Improve the robots remaining check. 
Currently the thereIsOneLastSurvivor() checks the size of the vector of robots. This function is called every iteration. 
Since the function is calling a method that iterates through the vector, the function has a linear run-time (O(n)) I believe we can get it to a constant run-time (O(1)).
Implimentation: Having a global variable to keep track of the vector's size. Then compare that in the thereIsOneLastSurvivor() function. This would increase the performance of the program.

**Comment by VinceBackpack** [comment]
Wow, Thanks. I'll pick this one up.

**Comment by PopeSpaceous** [comment]
@VinceBackpack The maintainer is a bit slow to respond, sometimes a couple days, so just work on it and submit your PR
