### ISSUE TITLE
Add #hacktoberfest hashtag from Twitter

### ISSUE THREAD

**Issue by seanprashad** [humphd/hacktoberfest-at-seneca-2018#8]
As hacktoberfest 2018 begins, the [#hacktoberfest](https://twitter.com/hashtag/hacktoberfest?lang=en) hashtag will start to get busy (_there's already some buzz happening_) - we should be a part of this and showcase the great work that will happen over the next four weeks.

![image](https://user-images.githubusercontent.com/13009507/46261201-28138b80-c4be-11e8-8e57-d892b1c65f15.png)

**Comment by humphd** [comment]
See also #3 and #7, which should give us a nice visual we can post in social media.
